sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 060709
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8gqtwcb1akgUr2jhvs
    access-key-secret: qMILhlIwX6onVp7onfHCouD0bAPFZN
    bucket-name: sky-itcast-pdf
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
